{% set name = "deffcode" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/deffcode-{{ version }}.tar.gz
  sha256: 7a3670c82a554316e3aafdcfd5755064fc0331b054817f8e6b7d81c549609692

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - cython
    - numpy
    - requests
    - colorlog
    - tqdm

test:
  imports:
    - deffcode
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://abhitronix.github.io/deffcode
  summary: A cross-platform High-performance & Flexible Real-time Video Frames Decoder in Python.
  dev_url: https://github.com/abhiTronix/deffcode
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - roaldarbol
